# Generated by Django 4.1.7 on 2023-02-27 09:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="email",
        ),
        migrations.RemoveField(
            model_name="surgeon",
            name="email",
        ),
    ]
