version: 2

on:
  pull_request_target:
    branches:
      - 'development/**'


updates:
  - package-ecosystem: "pip"
    schedule:
      interval: "monthly"
    rebase-strategy: "auto"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
