comment: false
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5%
        base: auto
        only_pulls: true
    patch:
      default:
        target: auto
        threshold: 5%
        base: auto
        only_pulls: true
