[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "booking_system.settings"
FAIL_INVALID_TEMPLATE_VARS = true
norecursedirs = "venv venv3 env env3 .texlive node_modules docs"
addopts = "--tb=short --showlocals -rxs --strict-markers --show-capture=no"

[tool.black]
line-length = 88
include = '\.pyi?$'
target-version = ['py310']


[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 88


[tool.pydocstyle]
add_ignore = "D1"
match-dir = '(?!test|docs|venv|\.).*'


[tool.coverage]
[tool.coverage.run]
source = ["."]
omit = ["conftest.py", "manage.py",
    "*/tests/*", "*/test_*.py",
  "*/baker_recipes.py",
  "*/migrations/",
  "*/urls.py",
  "*/conftest.py",]

[tool.coverage.report]
ignore_errors = true
show_missing = true