# Generated by Django 4.1.7 on 2023-02-27 00:52

import datetime

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models

import appointments.models
import common.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("health_providers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("start_datetime", models.DateTimeField(verbose_name="Start time")),
                ("end_datetime", models.DateTimeField(verbose_name="End time")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("requested", "requested"),
                            ("confirmed", "confirmed"),
                            ("rejected", "rejected"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appointment",
                "verbose_name_plural": "Appointments",
            },
        ),
        migrations.CreateModel(
            name="SurgeonAvailabilitySlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_datetime",
                    models.DateTimeField(
                        validators=[common.validators.DateTimeValidator()],
                        verbose_name="Available from",
                    ),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(
                        validators=[common.validators.DateTimeValidator()],
                        verbose_name="To",
                    ),
                ),
                (
                    "visit_duration",
                    models.DurationField(
                        default=datetime.timedelta(seconds=2700),
                        help_text="HH:MM:SS",
                        validators=[appointments.models.validate_slots_compatibility],
                        verbose_name="visit duration",
                    ),
                ),
                (
                    "health_provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="health_providers.healthprovider",
                    ),
                ),
            ],
            options={
                "verbose_name": "Surgeon Appointment Availability Slot",
                "verbose_name_plural": "Surgeon Appointment Availability Slots",
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
