# Generated by Django 4.1.7 on 2023-02-27 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="surgeonavailabilityslot",
            name="surgeon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.surgeon"
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="appointment_slot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="appointments.surgeonavailabilityslot",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.patient",
            ),
        ),
    ]
